apiVersion: apps/v1
kind: Deployment
metadata:
  name: meditrack-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meditrack
  template:
    metadata:
      labels:
        app: meditrack
    spec:
      containers:
        - name: meditrack
          image: harryshots/meditrack:latest
          ports:
            - containerPort: 5000

          envFrom:
            - configMapRef:
                name: meditrack-config

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10

          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"